from __future__ import annotations

import argparse
from pathlib import Path

from .extract import extract_circuit_from_checkpoint
from .gates import verilog_gate_expr
from .ir import GATE_NAMES, GateInput, GateNode, RegularCircuitIR
from .naming import default_pruned_module_name, module_name_from_metadata
from .prune import BoolSource, NaivePrunedCircuit, naive_prune_regular_circuit, reindex_pruned_circuit


HEADER = """// -----------------------------------------------------------------------------
// Auto-generated by compactlogic/compiler/verilog.py
// Target estimation default: AMD/Xilinx ZCU104 (tool flow to be added separately)
// This backend emits flattened Boolean circuits extracted from compactlogic checkpoints.
// -----------------------------------------------------------------------------
"""


ReductionStyle = str

def _default_pruned_module_name(metadata: dict[str, object], reduction_style: ReductionStyle) -> str:
    return default_pruned_module_name(metadata, reduction_style)


def _signal_ref(source: GateInput, input_dim: int) -> str:
    if source.const_value is not None:
        return f"1'b{source.const_value}"
    assert source.signal_id is not None
    signal_id = source.signal_id
    return f"in_bits[{signal_id}]" if signal_id < input_dim else f"node_bits[{signal_id}]"


def _gate_expr(node: GateNode, input_dim: int) -> str:
    a = _signal_ref(node.input_a, input_dim)
    b = _signal_ref(node.input_b, input_dim)
    return verilog_gate_expr(node.gate_id, a, b)


def _bit_to_score_term(signal_id: int, input_dim: int, width: int) -> str:
    bit = _signal_ref(GateInput(signal_id=signal_id), input_dim)
    if width == 1:
        return bit
    zeros = width - 1
    return f"{{{zeros}'d0, {bit}}}"


def _bool_source_term(source: BoolSource, input_dim: int, width: int) -> str:
    if source.const_value is not None:
        if width == 1:
            return f"1'b{source.const_value}"
        return f"{width}'d{source.const_value}"
    bit = _signal_ref(GateInput(signal_id=source.signal_id), input_dim)
    if source.inverted:
        bit = f"~{bit}"
    if width == 1:
        return bit
    zeros = width - 1
    return f"{{{zeros}'d0, {bit}}}"


def _linear_sum_expr(terms: list[str], width: int) -> str:
    if not terms:
        return f"{width}'d0"
    first, *rest = terms
    lines = [first]
    for term in rest:
        lines.append(f"    + {term}")
    return "\n".join(lines)


def _emit_reduction_assignments(
    *,
    lhs: str,
    terms: list[str],
    width: int,
    reduction_style: ReductionStyle,
    temp_prefix: str,
) -> list[str]:
    if reduction_style == "linear":
        return [f"    assign {lhs} =", f"        {_linear_sum_expr(terms, width)};"]
    if reduction_style != "balanced":
        raise ValueError(f"Unsupported reduction_style: {reduction_style!r}")

    if not terms:
        return [f"    assign {lhs} = {width}'d0;"]
    if len(terms) == 1:
        return [f"    assign {lhs} = {terms[0]};"]

    lines: list[str] = []
    current_terms = list(terms)
    level = 0
    while len(current_terms) > 1:
        next_terms: list[str] = []
        for pair_idx in range(0, len(current_terms), 2):
            left = current_terms[pair_idx]
            if pair_idx + 1 >= len(current_terms):
                next_terms.append(left)
                continue
            right = current_terms[pair_idx + 1]
            wire_name = f"{temp_prefix}_lvl{level}_{pair_idx // 2}"
            lines.append(f"    wire [{width - 1}:0] {wire_name};")
            lines.append(f"    assign {wire_name} = {left} + {right};")
            next_terms.append(wire_name)
        lines.append("")
        current_terms = next_terms
        level += 1

    lines.append(f"    assign {lhs} = {current_terms[0]};")
    return lines


def emit_regular_verilog(circuit: RegularCircuitIR, module_name: str | None = None) -> str:
    """Emit synthesizable Verilog for an unpruned extracted compactlogic circuit."""
    module_name = module_name or module_name_from_metadata(circuit.metadata)
    score_width = max(1, (circuit.output.group_size + 1).bit_length())
    total_scores_width = circuit.output.num_classes * score_width
    max_node_id = circuit.total_signal_count - 1

    lines: list[str] = [HEADER.rstrip(), ""]
    lines.append(f"module {module_name} (")
    lines.append(f"    input  wire [{circuit.input_dim - 1}:0] in_bits,")
    lines.append(f"    output wire [{total_scores_width - 1}:0] class_counts_flat")
    lines.append(");")
    lines.append("")
    lines.append(f"    // Model summary: {circuit.layer_count} regular layers, {circuit.node_count} Boolean nodes")
    lines.append(
        f"    // Output decoding: {circuit.output.num_classes} classes, group size {circuit.output.group_size}, tau={circuit.output.tau} (tau scaling omitted; argmax unchanged)"
    )
    lines.append("")
    lines.append(f"    wire [{max_node_id}:{circuit.input_dim}] node_bits;")
    lines.append("")

    for layer in circuit.layers:
        lines.append(f"    // Layer {layer.layer_index}: in_dim={layer.in_dim}, out_dim={layer.out_dim}")
        for node in layer.nodes:
            expr = _gate_expr(node, circuit.input_dim)
            gate_name = GATE_NAMES[node.gate_id]
            lines.append(
                f"    assign node_bits[{node.node_id}] = {expr};  // {gate_name}, a={node.input_a}, b={node.input_b}"
            )
        lines.append("")

    for class_idx, signal_ids in enumerate(circuit.output.groups()):
        lo = class_idx * score_width
        hi = lo + score_width - 1
        terms = [_bit_to_score_term(signal_id, circuit.input_dim, score_width) for signal_id in signal_ids if signal_id is not None]
        lines.append(f"    // Class {class_idx} population count")
        lines.extend(
            _emit_reduction_assignments(
                lhs=f"class_counts_flat[{hi}:{lo}]",
                terms=terms,
                width=score_width,
                reduction_style="linear",
                temp_prefix=f"class_{class_idx}_sum",
            )
        )
        lines.append("")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def emit_naive_pruned_verilog(
    pruned: NaivePrunedCircuit,
    module_name: str | None = None,
    *,
    reduction_style: ReductionStyle = "linear",
) -> str:
    """Emit synthesizable Verilog for the stage-1 naive-pruned regular circuit."""
    module_name = module_name or _default_pruned_module_name(pruned.metadata, reduction_style)
    score_width = max(1, (len(pruned.class_groups[0]) + 1).bit_length())
    total_scores_width = pruned.num_classes * score_width
    max_node_id = max((node.node_id for node in pruned.nodes), default=pruned.input_dim - 1)

    lines: list[str] = [HEADER.rstrip(), ""]
    lines.append(f"module {module_name} (")
    lines.append(f"    input  wire [{pruned.input_dim - 1}:0] in_bits,")
    lines.append(f"    output wire [{total_scores_width - 1}:0] class_counts_flat")
    lines.append(");")
    lines.append("")
    lines.append(f"    // Stage-1 naive-pruned model summary: {pruned.bop_count} Boolean nodes kept")
    lines.append("    // Pruning removes unreachable logic plus constant / identity / negation nodes by rewiring")
    lines.append(f"    // Output reduction style: {reduction_style}")
    lines.append("")
    if max_node_id >= pruned.input_dim:
        lines.append(f"    wire [{max_node_id}:{pruned.input_dim}] node_bits;")
        lines.append("")

    for node in pruned.nodes:
        expr = _gate_expr(node, pruned.input_dim)
        gate_name = GATE_NAMES[node.gate_id]
        lines.append(
            f"    assign node_bits[{node.node_id}] = {expr};  // {gate_name}, a={node.input_a}, b={node.input_b}"
        )
    if pruned.nodes:
        lines.append("")

    for class_idx, sources in enumerate(pruned.class_groups):
        lo = class_idx * score_width
        hi = lo + score_width - 1
        terms = [_bool_source_term(source, pruned.input_dim, score_width) for source in sources]
        lines.append(f"    // Class {class_idx} population count after stage-1 pruning")
        lines.extend(
            _emit_reduction_assignments(
                lhs=f"class_counts_flat[{hi}:{lo}]",
                terms=terms,
                width=score_width,
                reduction_style=reduction_style,
                temp_prefix=f"class_{class_idx}_sum",
            )
        )
        lines.append("")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def emit_regular_verilog_from_checkpoint(
    checkpoint_path: str | Path,
    metadata_path: str | Path | None = None,
    module_name: str | None = None,
) -> str:
    circuit = extract_circuit_from_checkpoint(checkpoint_path, metadata_path)
    return emit_regular_verilog(circuit, module_name=module_name)


def emit_naive_pruned_verilog_from_checkpoint(
    checkpoint_path: str | Path,
    metadata_path: str | Path | None = None,
    module_name: str | None = None,
    *,
    reindex: bool = False,
    reduction_style: ReductionStyle = "linear",
) -> str:
    circuit = extract_circuit_from_checkpoint(checkpoint_path, metadata_path)
    pruned = naive_prune_regular_circuit(circuit)
    if reindex:
        pruned = reindex_pruned_circuit(pruned)
    return emit_naive_pruned_verilog(pruned, module_name=module_name, reduction_style=reduction_style)


def main() -> None:
    parser = argparse.ArgumentParser(description="Emit compiled Verilog from a compactlogic checkpoint.")
    parser.add_argument("--checkpoint", type=Path, required=True, help="Path to ckpt_best_*.pt")
    parser.add_argument("--metadata", type=Path, default=None, help="Optional path to sibling meta_data.json")
    parser.add_argument("--output", type=Path, required=True, help="Path to write the generated .v file")
    parser.add_argument("--module-name", type=str, default=None, help="Optional custom Verilog module name")
    parser.add_argument(
        "--prune",
        choices=("none", "naive"),
        default="none",
        help="Optional pruning stage to apply before emission.",
    )
    parser.add_argument(
        "--reindex",
        action="store_true",
        help="After pruning, compact surviving internal node ids before emission.",
    )
    parser.add_argument(
        "--reduction-style",
        choices=("linear", "balanced"),
        default="linear",
        help="How to implement output population-count reduction in emitted Verilog.",
    )
    args = parser.parse_args()

    if args.reindex and args.prune != "naive":
        parser.error("--reindex currently requires --prune naive")
    if args.reduction_style != "linear" and args.prune != "naive":
        parser.error("--reduction-style balanced currently requires --prune naive")

    if args.prune == "naive":
        verilog = emit_naive_pruned_verilog_from_checkpoint(
            args.checkpoint,
            args.metadata,
            args.module_name,
            reindex=args.reindex,
            reduction_style=args.reduction_style,
        )
    else:
        verilog = emit_regular_verilog_from_checkpoint(args.checkpoint, args.metadata, args.module_name)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(verilog, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
